CREATE TABLE SNEAKER(
        ID INT AUTO_INCREMENT,
        CODE VARCHAR(225),
        BRAND_NAME VARCHAR(225),
        MODEL VARCHAR(225),
        SNK_SIZE DOUBLE,
        PICTURE VARCHAR(225),
		PRICE DOUBLE,
        RELEASE_DATE DATE,
        STAR_RATING VARCHAR(225),
        IMAGE_URL VARCHAR(2000),
		DESCRIPTION VARCHAR(2000)
);
	